export default {
  id: 3087,
  name: 'Mozzarella Basket',
  slug: 'mozzarella-basket',
  permalink: 'https: //www.carmelosoulkitchen.com/menu/mozzarella-basket/',
  date_created: '2021-05-28T09: 47: 11',
  date_created_gmt: '2021-05-28T07: 47: 11',
  date_modified: '2021-06-03T20: 55: 15',
  date_modified_gmt: '2021-06-03T18: 55: 15',
  type: 'variable',
  status: 'publish',
  featured: false,
  catalog_visibility: 'visible',
  description:
    '<p class="p1">Cestino di Mozzarella con tartare di salmone o rivisitazione della caprese fresca e vegetariana</p>\n',
  short_description: '',
  sku: '',
  price: '9',
  regular_price: '',
  sale_price: '',
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  purchasable: true,
  total_sales: 0,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  external_url: '',
  button_text: '',
  tax_status: 'taxable',
  tax_class: '',
  manage_stock: false,
  stock_quantity: null,
  backorders: 'no',
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  sold_individually: false,
  weight: '',
  dimensions: { length: '', width: '', height: '' },
  shipping_required: true,
  shipping_taxable: true,
  shipping_class: '',
  shipping_class_id: 0,
  reviews_allowed: false,
  average_rating: '0.00',
  rating_count: 0,
  upsell_ids: [],
  cross_sell_ids: [],
  parent_id: 0,
  purchase_note: '',
  categories: [{ id: 213, name: 'Fresh Snacks', slug: 'fresh-snacks' }],
  tags: [],
  images: [
    {
      id: 3060,
      date_created: '2021-05-28T01: 36: 28',
      date_created_gmt: '2021-05-27T21: 36: 28',
      date_modified: '2021-05-28T01: 36: 28',
      date_modified_gmt: '2021-05-27T21: 36: 28',
      src: 'https: //www.carmelosoulkitchen.com/wp-content/uploads/2021/05/MOZZARELLA-BASKET-fs8.png',
      name: 'MOZZARELLA BASKET-fs8',
      alt: ''
    }
  ],
  attributes: [
    {
      id: 0,
      name: 'Variante',
      position: 0,
      visible: true,
      variation: true,
      options: [Array]
    }
  ],
  default_attributes: [{ id: 0, name: 'Variante', option: 'Capri' }],
  variations: [3088, 3089],
  grouped_products: [],
  menu_order: 0,
  price_html: `<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&euro;</span>9<sup>,
  00</sup></bdi></span> &ndash; <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&euro;</span>12<sup>,
  00</sup></bdi></span>`,
  related_ids: [3075, 3082],
  meta_data: [
    { id: 37160, key: 'lafka_rev_slider_before_header', value: '0' },
    { id: 37161, key: 'lafka_prtfl_custom_content', value: '0' },
    {
      id: 37162,
      key: '_last_editor_used_jetpack',
      value: 'classic-editor'
    },
    {
      id: 37249,
      key: '_yoast_wpseo_primary_product_cat',
      value: '174'
    },
    { id: 37251, key: '_lafka_nutrition_energy', value: '' },
    { id: 37252, key: '_lafka_nutrition_protein', value: '' },
    { id: 37253, key: '_lafka_nutrition_fat', value: '' },
    { id: 37254, key: '_lafka_nutrition_satfat', value: '' },
    { id: 37255, key: '_lafka_nutrition_carbs', value: '' },
    { id: 37256, key: '_lafka_nutrition_sugars', value: '' },
    { id: 37257, key: '_lafka_nutrition_sodium', value: '' },
    { id: 37258, key: '_lafka_product_allergens', value: '' },
    { id: 37259, key: '_product_addons', value: [] },
    { id: 37260, key: '_product_addons_exclude_global', value: '0' },
    { id: 37261, key: '_woosea_brand', value: '' },
    { id: 37262, key: '_woosea_mpn', value: '' },
    { id: 37263, key: '_woosea_upc', value: '' },
    { id: 37264, key: '_woosea_ean', value: '' },
    { id: 37265, key: '_woosea_gtin', value: '' },
    { id: 37266, key: '_woosea_color', value: '' },
    { id: 37267, key: '_woosea_size', value: '' },
    { id: 37268, key: '_woosea_gender', value: '' },
    { id: 37269, key: '_woosea_material', value: '' },
    { id: 37270, key: '_woosea_pattern', value: '' },
    { id: 37271, key: '_woosea_optimized_title', value: '' },
    { id: 37272, key: '_woosea_unit_pricing_measure', value: '' },
    { id: 37273, key: '_woosea_unit_pricing_base_measure', value: '' },
    { id: 37274, key: '_woosea_condition', value: '' },
    { id: 37275, key: '_woosea_age_group', value: '' },
    { id: 37276, key: '_woosea_installment_months', value: '' },
    { id: 37277, key: '_woosea_installment_amount', value: '' },
    { id: 37278, key: '_woosea_exclude_product', value: 'no' },
    { id: 37279, key: '_woosea_cost_of_good_sold', value: '' },
    { id: 37280, key: '_woosea_multipack', value: '' },
    { id: 37281, key: '_woosea_is_bundle', value: '' },
    { id: 37282, key: '_woosea_energy_efficiency_class', value: '' },
    {
      id: 37283,
      key: '_woosea_min_energy_efficiency_class',
      value: ''
    },
    {
      id: 37284,
      key: '_woosea_max_energy_efficiency_class',
      value: ''
    },
    { id: 37285, key: '_woosea_is_promotion', value: '' },
    { id: 37286, key: '_woosea_custom_field_0', value: '' },
    { id: 37287, key: '_woosea_custom_field_1', value: '' },
    { id: 37288, key: '_woosea_custom_field_2', value: '' },
    { id: 37289, key: '_woosea_custom_field_3', value: '' },
    { id: 37290, key: '_woosea_custom_field_4', value: '' },
    { id: 37291, key: 'woopt_actions', value: [Array] },
    { id: 37292, key: '_wpm_gtin_code', value: '' },
    { id: 37293, key: '_wpm_gtin_code_label', value: '' },
    { id: 37294, key: '_wc_facebook_commerce_enabled', value: 'no' },
    {
      id: 37295,
      key: 'fb_product_group_id',
      value: '5616050951801757'
    },
    { id: 37296, key: 'rs_page_bg_color', value: '' },
    { id: 37297, key: 'lafka_layout', value: 'default' },
    { id: 37298, key: 'lafka_top_header', value: 'default' },
    { id: 37299, key: 'lafka_footer_style', value: 'default' },
    { id: 37300, key: 'lafka_footer_size', value: 'default' },
    { id: 37301, key: 'lafka_header_size', value: 'default' },
    { id: 37302, key: 'lafka_video_bckgr_url', value: '' },
    { id: 37303, key: 'lafka_video_bckgr_start', value: '' },
    { id: 37304, key: 'lafka_video_bckgr_end', value: '' },
    { id: 37305, key: 'lafka_video_bckgr_loop', value: '0' },
    { id: 37306, key: 'lafka_video_bckgr_mute', value: '0' },
    { id: 37307, key: 'lafka_product_video_url', value: '' },
    {
      id: 37308,
      key: 'lafka_single_product_gallery_type',
      value: 'default'
    },
    { id: 37309, key: '_wpb_vc_js_status', value: 'false' },
    { id: 37310, key: '_yoast_wpseo_content_score', value: '60' },
    {
      id: 37311,
      key: '_yoast_wpseo_estimated-reading-time-minutes',
      value: '1'
    }
  ],
  stock_status: 'instock',
  ean_code: '',
  _links: { self: [[Object]], collection: [[Object]] }
}
